shopflow_analytics:
  target: dev
  outputs:
    dev:
      type: databricks
      host: "dbc-db486585-cff7.cloud.databricks.com"
      http_path: "/sql/1.0/warehouses/233098644a6a2c6f"
      schema: silver
      catalog: shopflow_analytics_cat
      token: "dapi3bb0721c7d7af2e70f233a4a4756c951"
      threads: 4
      connect_timeout: 60
      connect_retries: 3

    prod:
      type: databricks
      host: "{{ env_var('DATABRICKS_HOST', 'dbc-db486585-cff7.cloud.databricks.com') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'silver') }}"
      catalog: "{{ env_var('DATABRICKS_CATALOG', 'shopflow_analytics_cat') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
      connect_timeout: 60
      connect_retries: 3
